#ifndef __LCD_DRV_H_
#define __LCD_DRV_H_

struct imx6ull_lcdif{
	volatile unsigned int CTRL;
	volatile unsigned int CTRL_SET;
	volatile unsigned int CTRL_CLR;
	volatile unsigned int CTRL_TOG;
	volatile unsigned int CTRL1;
	volatile unsigned int CTRL1_SET;
	volatile unsigned int CTRL1_CLR;
	volatile unsigned int CTRL1_TOG;
	volatile unsigned int CTRL2;
	volatile unsigned int CTRL2_SET;
	volatile unsigned int CTRL2_CLR;
	volatile unsigned int CTRL2_TOG;
	volatile unsigned int TRANSFER_COUNT;
	unsigned char RESERVED_0[12];
	volatile unsigned int CUR_BUF;
	unsigned char RESERVED_1[12];
	volatile unsigned int NEXT_BUF;
	unsigned char RESERVED_2[12];
	volatile unsigned int TIMING;
	unsigned char RESERVED_3[12];
	volatile unsigned int VDCTRL0;
	volatile unsigned int VDCTRL0_SET;
	volatile unsigned int VDCTRL0_CLR;
	volatile unsigned int VDCTRL0_TOG;
	volatile unsigned int VDCTRL1;
	unsigned char RESERVED_4[12];
	volatile unsigned int VDCTRL2;
	unsigned char RESERVED_5[12];
	volatile unsigned int VDCTRL3;
	unsigned char RESERVED_6[12];
	volatile unsigned int VDCTRL4;
	unsigned char RESERVED_7[12];
	volatile unsigned int DVICTRL0;
	unsigned char RESERVED_8[12];
	volatile unsigned int DVICTRL1;
	unsigned char RESERVED_9[12];
	volatile unsigned int DVICTRL2;
	unsigned char RESERVED_10[12];
	volatile unsigned int DVICTRL3;
	unsigned char RESERVED_11[12];
	volatile unsigned int DVICTRL4;
	unsigned char RESERVED_12[12];
	volatile unsigned int CSC_COEFF0;
	unsigned char RESERVED_13[12];
	volatile unsigned int CSC_COEFF1;
	unsigned char RESERVED_14[12];
	volatile unsigned int CSC_COEFF2;
	unsigned char RESERVED_15[12];
	volatile unsigned int CSC_COEFF3;
	unsigned char RESERVED_16[12];
	volatile unsigned int CSC_COEFF4;
	unsigned char RESERVED_17[12];
	volatile unsigned int CSC_OFFSET;
	unsigned char RESERVED_18[12];
	volatile unsigned int CSC_LIMIT;
	unsigned char RESERVED_19[12];
	volatile unsigned int DATA;
	unsigned char RESERVED_20[12];
	volatile unsigned int BM_ERROR_STAT;
	unsigned char RESERVED_21[12];
	volatile unsigned int CRC_STAT;
	unsigned char RESERVED_22[12];
	volatile  unsigned int STAT;
	unsigned char RESERVED_23[76];
	volatile unsigned int THRES;
	unsigned char RESERVED_24[12];
	volatile unsigned int AS_CTRL;
	unsigned char RESERVED_25[12];
	volatile unsigned int AS_BUF;
	unsigned char RESERVED_26[12];
	volatile unsigned int AS_NEXT_BUF;
	unsigned char RESERVED_27[12];
	volatile unsigned int AS_CLRKEYLOW;
	unsigned char RESERVED_28[12];
	volatile unsigned int AS_CLRKEYHIGH;
	unsigned char RESERVED_29[12];
	volatile unsigned int SYNC_DELAY;
};

#endif
